apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
    - name: ui
      image: dual-docker-example_ui:latest
      command: ["yarn", "start"]
      imagePullPolicy: Never
      env:
        - name: PORT
          value: "8080"
